// 1 - fullscreenbg 2.2 _ http://github.com/setetres/fullscreenbg
// 2 - fitvids 1.1 _ http://github.com/davatron5000/FitVids.js

// 1 - fullscreenbg 2.2 _ http://github.com/setetres/fullscreenbg

(function($){var optionsArr={selector:"img, video, iframe"};$.fn.fullscreenbg=function(options){if(options)$.extend(optionsArr,options);this.each(function(){var parentElement=this;var image=$("img",$(this));if(image.length>0){if(isImageLoaded(image[0])){setCrop();}else{image.on("load",setCrop);}}else{setCrop();} function setCrop(){$(window).resize(function(){fillBg(optionsArr.selector,parentElement);});fillBg(optionsArr.selector,parentElement);}})};function isImageLoaded(img){if(!img.completed&&img.naturalWidth==0){return false;} return true;} function fillBg(selector,parentobj){var parentHeight=$(parentobj).parent().height();var parentWidth=$(parentobj).parent().width();$(selector,parentobj).each(function(){var imgHeight=$(this).height();var imgWidth=$(this).width();var bleed=5;var newWidth=parentWidth+bleed;var newHeight=((parentWidth / imgWidth)*imgHeight)+bleed;var topMargin=-((newHeight-parentHeight)/ 2);var leftMargin=-(bleed / 2);if(newHeight<parentHeight){var newWidth=((parentHeight / imgHeight)*imgWidth)+bleed;var newHeight=parentHeight+bleed;var topMargin=-(bleed / 2);var leftMargin=-((newWidth-parentWidth)/ 2);} $(this).css({height:newHeight+"px",width:newWidth+"px",marginLeft:leftMargin+"px",marginTop:topMargin+"px"}).show(0);});}})(jQuery);

// 2 - fitvids 1.1 _ http://github.com/davatron5000/FitVids.js

(function ($){"use strict";$.fn.fitVids=function (options){var settings={customSelector:null,ignore:null};if(!document.getElementById('fit-vids-style')){var head=document.head||document.getElementsByTagName('head')[0];var css='.fluid-width-video-wrapper{width:100%;position:relative;padding:0;}.fluid-width-video-wrapper iframe,.fluid-width-video-wrapper object,.fluid-width-video-wrapper embed {position:absolute;top:0;left:0;width:100%;height:100%;}';var div=document.createElement('div');div.innerHTML='<p>x</p><style id="fit-vids-style">'+css+'</style>';head.appendChild(div.childNodes[1]);}if(options){$.extend(settings,options);}return this.each(function (){var selectors=["iframe[src*='player.vimeo.com']","iframe[src*='youtube.com']","iframe[src*='youtube-nocookie.com']","iframe[src*='kickstarter.com'][src*='video.html']","object","embed"];if(settings.customSelector){selectors.push(settings.customSelector);}var ignoreList='.fitvidsignore';if(settings.ignore){ignoreList=ignoreList+', '+settings.ignore;}var $allVideos=$(this).find(selectors.join(','));$allVideos=$allVideos.not("object object");$allVideos=$allVideos.not(ignoreList);$allVideos.each(function (){var $this=$(this);if($this.parents(ignoreList).length>0){return;}if(this.tagName.toLowerCase()==='embed'&&$this.parent('object').length||$this.parent('.fluid-width-video-wrapper').length){return;}if((!$this.css('height')&&!$this.css('width'))&&(isNaN($this.attr('height'))||isNaN($this.attr('width')))){$this.attr('height',9);$this.attr('width',16);}var height=(this.tagName.toLowerCase()==='object'||($this.attr('height')&&!isNaN(parseInt($this.attr('height'),10))))?parseInt($this.attr('height'),10):$this.height(),width=!isNaN(parseInt($this.attr('width'),10))?parseInt($this.attr('width'),10):$this.width(),aspectRatio=height/width;if(!$this.attr('id')){var videoID='fitvid'+Math.floor(Math.random()*999999);$this.attr('id',videoID);}$this.wrap('<div class="fluid-width-video-wrapper"></div>').parent('.fluid-width-video-wrapper').css('padding-top',(aspectRatio*100)+"%");$this.removeAttr('height').removeAttr('width');});});};})(window.jQuery||window.Zepto);
